I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 43, in script
    quyang "test"
Exception: Sayer 'quyang' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 43, in script
    quyang "test"
  File "/Users/robertliang/Desktop/renpy-7.5.3-sdk/renpy/ast.py", line 2573, in execute
    Say.execute(self)
  File "/Users/robertliang/Desktop/renpy-7.5.3-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/robertliang/Desktop/renpy-7.5.3-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'quyang' is not defined.

macOS-14.1.1-arm64-arm-64bit arm64
Ren'Py 8.3.2.24090902
Reloaded_Gaming_Girls 1.0
Fri Nov  1 05:40:45 2024
